name: tmdb_clone_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  http: ^0.13.5
  retrofit: '>=4.0.0 <5.0.0'
  logger: any
  dio: ^5.1.2  
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  image_fade: ^0.6.2
  rate: ^0.0.1
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.11
  intl: ^0.18.1
  auto_route: ^7.4.0
  mocktail: ^0.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.4
  json_serializable: ^6.6.2
  retrofit_generator: ^7.0.1
  auto_route_generator: ^7.1.1

flutter:
  uses-material-design: true
